name: Deploy and Set Environment Variables

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or your preferred Node.js version

    - name: Create package.json
      run: |
        echo '{"name":"your-project-name","version":"1.0.0","scripts":{"build":"echo \"No build specified\""}}' > package.json

    - name: Install dependencies
      run: npm ci  # This should now work with the minimal package.json

    - name: Replace placeholders
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        sed -i 's/process.env.TELEGRAM_BOT_TOKEN/"${{ secrets.TELEGRAM_BOT_TOKEN }}"/g' index.html
        sed -i 's/process.env.TELEGRAM_CHAT_ID/"${{ secrets.TELEGRAM_CHAT_ID }}"/g' index.html

    # Add your deployment steps here
    # For example:
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: .
