name: Deploy and Set Environment Variables
on:
  push:
    branches:
      - main  # or your default branch name
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Replace placeholders
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        sed -i "s/PLACEHOLDER_TOKEN/${{ secrets.TELEGRAM_BOT_TOKEN }}/" index.html
        sed -i "s/PLACEHOLDER_CHAT_ID/${{ secrets.TELEGRAM_CHAT_ID }}/" index.html
        echo "Replacement complete. Checking result:"
        grep "telegramBotToken" index.html
        grep "chatId" index.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
