name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Replace placeholders with secrets
        run: |
          sed -i 's/YOUR_BOT_TOKEN_PLACEHOLDER/${{ secrets.TELEGRAM_BOT_TOKEN }}/g' index.html
          sed -i 's/YOUR_CHAT_ID_PLACEHOLDER/${{ secrets.TELEGRAM_CHAT_ID }}/g' index.html
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Replace placeholders with secrets" || echo "No changes to commit"
      
      - name: Push changes
        run: git push
      
      - name: Send Telegram notification
        if: success()
        run: |
          MESSAGE="Website updated successfully. Please check https://vikash888.github.io/Vicky-Web/"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="$MESSAGE"
